// <auto-generated />
using System;
using BogsyVideoStoreRS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BogsyVideoStoreRS.Migrations
{
    [DbContext(typeof(BvsDbContext))]
    [Migration("20260327092627_AddVideoIsArchived")]
    partial class AddVideoIsArchived
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BogsyVideoStoreRS.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Manila, PH",
                            Contact = "09123456789",
                            CreatedAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Juan Dela Cruz"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Bulacan, PH",
                            Contact = "09876543210",
                            CreatedAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Maria Clara"
                        });
                });

            modelBuilder.Entity("BogsyVideoStoreRS.Models.Rental", b =>
                {
                    b.Property<string>("RentalId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Penalty")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("RentDate")
                        .HasColumnType("date");

                    b.Property<decimal>("RentFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("RentalId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VideoId");

                    b.ToTable("Rentals", t =>
                        {
                            t.HasCheckConstraint("CHK_Status", "[Status] IN ('Active', 'Overdue', 'Returned')");
                        });

                    b.HasData(
                        new
                        {
                            RentalId = "R-1001",
                            CreatedAt = new DateTime(2023, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            DueDate = new DateOnly(2023, 10, 27),
                            Penalty = 0m,
                            RentDate = new DateOnly(2023, 10, 25),
                            RentFee = 25m,
                            Status = "Active",
                            VideoId = 1
                        },
                        new
                        {
                            RentalId = "R-1002",
                            CreatedAt = new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            DueDate = new DateOnly(2023, 10, 27),
                            Penalty = 0m,
                            RentDate = new DateOnly(2023, 10, 26),
                            RentFee = 25m,
                            Status = "Active",
                            VideoId = 4
                        },
                        new
                        {
                            RentalId = "R-1003",
                            CreatedAt = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            DueDate = new DateOnly(2023, 10, 23),
                            Penalty = 0m,
                            RentDate = new DateOnly(2023, 10, 20),
                            RentFee = 50m,
                            Status = "Overdue",
                            VideoId = 2
                        });
                });

            modelBuilder.Entity("BogsyVideoStoreRS.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRentDays")
                        .HasColumnType("int");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RentedCount")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("VideoId");

                    b.ToTable("Videos", t =>
                        {
                            t.HasCheckConstraint("CHK_Category", "[Category] IN ('DVD', 'VCD')");

                            t.HasCheckConstraint("CHK_MaxRentDays", "[MaxRentDays] BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CHK_Price", "[Price] IN (25, 50)");
                        });

                    b.HasData(
                        new
                        {
                            VideoId = 1,
                            Category = "VCD",
                            CreatedAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            MaxRentDays = 2,
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjA0NDY3NjI4NV5BMl5BanBnXkFtZTcwNjM5OTYyMw@@._V1_.jpg",
                            Price = 25m,
                            RentedCount = 2,
                            Stock = 3,
                            Title = "Madagascar"
                        },
                        new
                        {
                            VideoId = 2,
                            Category = "DVD",
                            CreatedAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            MaxRentDays = 3,
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTUxMzcxOTYxNl5BMl5BanBnXkFtZTcwMzUxNjYzMw@@._V1_.jpg",
                            Price = 50m,
                            RentedCount = 1,
                            Stock = 4,
                            Title = "Mr. and Mrs. Smith"
                        },
                        new
                        {
                            VideoId = 3,
                            Category = "DVD",
                            CreatedAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            MaxRentDays = 3,
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
                            Price = 50m,
                            RentedCount = 0,
                            Stock = 5,
                            Title = "Inception"
                        },
                        new
                        {
                            VideoId = 4,
                            Category = "VCD",
                            CreatedAt = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            MaxRentDays = 1,
                            PosterUrl = "https://m.media-amazon.com/images/I/51EG732BV3L._AC_.jpg",
                            Price = 25m,
                            RentedCount = 1,
                            Stock = 2,
                            Title = "The Matrix"
                        });
                });

            modelBuilder.Entity("BogsyVideoStoreRS.Models.Rental", b =>
                {
                    b.HasOne("BogsyVideoStoreRS.Models.Customer", "Customer")
                        .WithMany("Rentals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BogsyVideoStoreRS.Models.Video", "Video")
                        .WithMany("Rentals")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("BogsyVideoStoreRS.Models.Customer", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("BogsyVideoStoreRS.Models.Video", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
